# <center>I. Débuter avec Numpy</center>

Documentation du module Numpy : https://numpy.org/doc/

Il faut **exécuter la cellule ci-dessous** pour pouvoir lancer les exemples dans ce notebook.

In [2]:
import numpy as np

Pour connaître **votre version de Numpy**, tapez **np.__version__** après avoir importé **numpy** sous le nom **np**.

In [3]:
import numpy as np

np.__version__

'1.20.2'

### <center><u> I.1. Un scalaire </u></center>

Documentation de l'objet ndarray : https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

In [3]:
scalaire = np.array(1)
scalaire

array(1)

La variable <i>scalaire</i> est un objet issu de la classe "**ndarray**" ayant pour valeur array(1), alors qu'un nombre entier contenant la valeur 1 est un objet instancié de la classe "**int**".

In [4]:
scalaire = np.array(1)
print("Type de la variable scalaire :", type(scalaire))
print("Type d'un entier valant 1 :", type(1))

Type de la variable scalaire : <class 'numpy.ndarray'>
Type d'un entier valant 1 : <class 'int'>


### <center><u> I.2. Un tableau à 1 dimension </u></center>

Un **ndarray de dimension 1**, permet de représenter des **vecteurs**.

In [10]:
vecteur = np.array([1,2,3])
vecteur

array([1, 2, 3])

La variable **vecteur** est un objet issu de la classe "**ndarray**" ayant pour valeur array([1,2,3]), ce qui est différent d'une liste (objet list) python qui aurait pour valeur [1,2,3].

In [8]:
vecteur = np.array([1,2,3])
print("Type de la variable vecteur :", type(vecteur))
print("Type d'une liste contenant [1,2,3] :", type([1,2,3]))

Type de la variable vecteur : <class 'numpy.ndarray'>
Type d'une liste contenant [1,2,3] : <class 'list'>


### <center><u> I.3. Un tableau à 2 dimensions </u></center>

Un **ndarray de dimension 2** permet de représenter **matrices**.

In [12]:
matrice = np.array([[1,2,3], [4,5,6]])
matrice

array([[1, 2, 3],
       [4, 5, 6]])

La variable **matrice** est un objet issu de la classe "**ndarray**" ayant pour valeur array([[1,2,3],[4,5,6]]), ce qui est différent d'une liste de listes qui aurait pour valeur [[1,2,3], [4,5,6]]

In [13]:
matrice = np.array([[1,2,3], [4,5,6]])
print("Type de la variable matrice :", type(matrice))
print("Type d'une liste de listes contenant [[1,2,3], [4,5,6]] :", type([[1,2,3], [4,5,6]]))

Type de la variable matrice : <class 'numpy.ndarray'>
Type d'une liste de listes contenant [[1,2,3], [4,5,6]] : <class 'list'>


### <center><u> I.4. Utiliser print avec un ndarray </u></center>

#### <center><u> I.4.1. Print un scalaire </u></center>

In [17]:
scalaire = np.array(0)
print(scalaire)

0


#### <center><u> I.4.2. Print un tableau à 1 dimension </u></center>

In [18]:
vecteur = np.array([1,2,3,4,5,6,7,8,9,10])
print(vecteur)

[ 1  2  3  4  5  6  7  8  9 10]


#### <center><u> I.4.2. Print un tableau à 2 dimensions </u></center>

In [20]:
matrice = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(matrice)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### <center><u> I.5. Connaître les dimensions d'un ndarray </u></center>

Documentation de ndarray.shape : https://numpy.org/devdocs/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape

L'attribut shape des objets ndarray renvoie un tuple comme ceci : (nombre_de_lignes, nombre_de_colonnes)

#### <center><u> I.5.1. Exemple 1 : un scalaire </u></center>

In [21]:
scalaire = np.array(10)
scalaire.shape

()

Le mot-clé **shape** est un attribut des ndarray et non une méthode. Il ne faut donc pas mettre de parenthèses!

#### <center><u> I.5.2. Exemple 2 : vecteurs </u></center>

In [25]:
vecteur = np.array([1,2])
vecteur.shape

(2,)

Le **vecteur ci-dessus contient deux lignes et aucune colonne**. L'attribut shape n'affiche pas 0, mais rien du tout, quand il n'y a pas de données sur une dimension.

In [26]:
vecteur = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
vecteur.shape

(12,)

Le **vecteur ci-dessus contient douze lignes et aucune colonne**.

#### <center><u> I.5.3. Exemple 3 : matrices </u></center>

In [29]:
matrice = np.array([[1,0,0], [0,1,0], [0,0,1]])
matrice.shape

(3, 3)

La **matrice ci-dessus possède 3 lignes et 3 colonnes**.

In [32]:
matrice = np.array([[1,2], [2,3], [3,4], [4,5]])
matrice.shape

(4, 2)

La **matrice ci-dessus possède 4 lignes et 2 colonnes**.

In [33]:
matrice = np.array([[1,2,3,4,5], [6,7,8,9,10]])
matrice.shape

(2, 5)

La **matrice ci-dessus possède 2 lignes et 5 colonnes**.

#### <center><u> I.5.4. L'attribut shape </u></center>

L'attribut **shape** étant un **tuple**, il est possible d'accéder à ses éléments grâce à un index.

**shape[0]** : indique le nombre de **lignes**

**shape[1]** : indique le nombre de **colonnes**

In [38]:
matrice = np.array([[1,2,3,4,5], [6,7,8,9,10]])
matrice.shape[0]

2

Ci-dessus, on accède au **premier indice** du tuple **shape** qui nous indique que le ndarray associé à la variable matrice contient **2 lignes**.

In [3]:
matrice = np.array([[1,2,3,4,5], [6,7,8,9,10]])
matrice.shape[1]

5

Ci-dessus, on accède au **second indice** du tuple **shape** qui nous indique que le ndarray associé à la variable matrice contient **5 colonnes**.

#### <center><u> I.5.5. Un vecteur avec une seule valeur </u></center>

Nous avons vu précédemment qu'un **scalaire ne possède pas de dimension**. Il est cependant possible de donner une dimension à un nombre entier. 

Pour ce faire, il faut l'écrire entre **crochets** [].

In [43]:
scalaire = np.array(0)
nombre_dimension_1 = np.array([0])
print(scalaire.shape)
print(nombre_dimension_1.shape)

()
(1,)


Vous pouvez imaginer la valeur donnée par **nombre_dimension_1**, comme **un point sur une ligne**. Autrement dit, comme un point, sur un graphique composé d'une seule dimension.

On peut donc constater que **np.array(0) != np.array([0])**

### <center><u> I.6. Les différences entre un objet list et un objet ndarray </u></center>

#### <center><u> 1.6.1. La méthode len() et l'attribut shape </u></center>

In [45]:
liste = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
len(liste)

11

Pour connaître sa **longueur** on utilise la méthode **len()** qui prend en paramètre la liste.

La liste ci-dessus possède **11 éléments**.

On va à présent créer une liste à 2 dimensions.

In [46]:
liste = [[-3,-2,-1], [1, 2, 3]]
len(liste)

2

Python nous indique que la liste ci-dessus possède **2 éléments**. En effet, la variable liste est une liste qui contient 2 listes. Ici, la variable len() nous indique combien de sous-listes sont contenues dans la variable liste.

On ne peut donc pas obtenir simplement le nombre de colonnes qui sont dans les listes internes, alors que pour un ndarray, l'attribut **shape** nous donne toutes les informations dont nous avons besoin sur **les dimensions de l'objet**.

Ci-dessous, on va instancier un ndarray avec la liste ci-dessus, et utiliser l'attribut shape pour connaître ses dimensions.

In [50]:
matrice = np.array([[-3,-2,-1], [1, 2, 3]])
matrice.shape

(2, 3)

#### <center><u> I.6.2. L'opérateur somme : + </u></center>

L'utilisation de l'opérateur **somme** sur deux listes va effectuer une **concaténation** des deux listes.

In [52]:
liste_1 = [1,2,3]
liste_2 = [4,5,6]
liste_1 + liste_2

[1, 2, 3, 4, 5, 6]

L'utilisateur de l'opérateur **somme** sur deux ndarray va procéder à une **addition**.

Commençons par une somme entre deux éléments de dimension 0.

In [53]:
scalaire_1 = np.array(1)
scalaire_2 = np.array(2)
somme_scalaire = scalaire_1 + scalaire_2
print(scalaire_1, "+", scalaire_2, "=", somme_scalaire)

1 + 2 = 3


**Somme entre deux vecteurs** représentés par des ndarray.

In [54]:
vecteur_1 = np.array([1, 2, 3])
vecteur_2 = np.array([-1, -2, -3])
somme_vecteur = vecteur_1 + vecteur_2
print(vecteur_1, "+", vecteur_2, "=", somme_vecteur)

[1 2 3] + [-1 -2 -3] = [0 0 0]


**Somme entre deux matrices** représentées par des ndarray

In [61]:
matrice_1 = np.array([[1,0,0], [0,1,0], [0,0,1]])
matrice_2 = np.array([[1,0,0], [0,1,0], [0,0,1]])
somme_matrice = matrice_1 + matrice_2
print(matrice_1)
print("    +")
print(matrice_2)
print("    =")
print(somme_matrice)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
    +
[[1 0 0]
 [0 1 0]
 [0 0 1]]
    =
[[2 0 0]
 [0 2 0]
 [0 0 2]]


#### <center><u> I.6.3. Les fonctions mathématiques </u></center>

**Appliquer une fonction mathématique à une liste**, par exemple la fonction log(), **ne fonctionne tout simplement pas**.

In [63]:
from math import log

liste = [1,2,3,4]
log(liste)

TypeError: must be real number, not list

Tandis que pour un **ndarray**, cela va **appliquer la fonction à tous les éléments** et **renvoyer un ndarray**.

Ici, on fait appel à la méthode log provenant du module np et non le module math.

In [66]:
vecteur = np.array([1,2,3,4])
np.log(vecteur)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

On peut le tester avec une autre fonction, par exemple, la fonction **sqrt()** qui permet de calculer la **racine carrée** (square root) d'un nombre ou d'un ndarray.

In [68]:
vecteur = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.sqrt(vecteur)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

#### <center><u> I.6.4. La longueur </u></center>

Une liste peut contenir des **listes ayant des longueurs différentes**.

In [69]:
liste_de_listes = [[1,2], [1,2,3], [1,2,3,4]]
liste_de_listes

[[1, 2], [1, 2, 3], [1, 2, 3, 4]]

Dans un ndarray à 2 dimensions, **tous les éléments doivent être de mêmes dimensions**, sinon cela provoque une erreur.

In [71]:
matrice_erreur = np.array([[1,2], [1,2,3], [1,2,3,4]])
matrice_erreur

<ipython-input-71-6ff51e93aea5>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matrice_erreur = np.array([[1,2], [1,2,3], [1,2,3,4]])


array([list([1, 2]), list([1, 2, 3]), list([1, 2, 3, 4])], dtype=object)