# <center>V. Slicing conditionnel et squeeze</center>

**Ne pas oublier d'exécuter la cellule ci-dessous** qui permet d'importer Numpy!

In [2]:
import numpy as np

# <center>V.1. Slicing conditionnel</center>

### <center><u>V.1.1. ndarray de booléens</u></center>

Il est possible d'utiliser des **structures conditionnelles** sur nos ndarray pour récupérer un nouvel ndarray contenant des booléens.

Prenons un exemple d'une matrice de dimension 4x4, et créons cette condition : **les éléments de la matrice qui sont supérieurs 6**.

In [19]:
matrice_b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
matrice_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
matrice_b > 6

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

On obtient une matrice de **même dimension**, et pour chaque élément, on a un **booléen correspondant à notre condition**. Ici, tous les indices où les valeurs de matrice_b étaient supérieures à 6 sont à True, les autres sont à False.

Prenons un second exemple avec une autre condition : **les éléments de la matrice qui sont pairs**.

In [17]:
matrice_b % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

On obtient une matrice de même dimension (4x4). Ici, toutes les valeurs aux **indices où les valeurs de matrice_b sont pairs** sont définis à True, les autres sont définis à False.

**Des conditions peuvent être établies entre un vecteur et une matrice** si ces deux ndarray respectent les règles du broadcasting que nous avons vues à l'épisode précédent.

In [21]:
vecteur_b = np.array([9,7,3,8])
vecteur_b

array([9, 7, 3, 8])

**Condition : les valeurs des éléments de la matrice qui sont supérieures ou égales aux valeurs des éléments du vecteur.**

In [23]:
matrice_b >= vecteur_b

array([[False, False,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Le **vecteur_b** subit un **broadcast** en matrice. vecteur_b = np.array([[9, 7, 3, 8], [9, 7, 3, 8], [9, 7, 3, 8], [9, 7, 3, 8]])

Ensuite **on compare chaque ligne élément par élément en applicant la condition**. On obtient alors une matrice de dimension 4x4, avec les booléens correspondant à notre condition.

### <center><u>V.1.2. Les valeurs répondant à la condition</u></center>

#### <center><u>V.1.2.1. Des conditions simples</u></center>

Pour obtenir les valeurs répondant à la condition, il faut indiquer **la condition entre crochets**.

Reprenons notre exemple, pour **les valeurs de la matrice qui sont supérieurs à 6**.

In [25]:
matrice_b[matrice_b > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

On récupère un **ndarray de dimension 1** indiquant toutes les **valeurs supérieures à 2** qu'il a pu trouver dans **matrice_b**.

On peut reprendre notre exemple avec notre conditions sur les **valeurs paires**.

In [26]:
matrice_b[matrice_b % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

On récupère un **ndarray de dimension1** indiquant toutes les **valeurs paires** qu'il a pu trouver dans **matrice_b**.

#### <center><u>V.1.2.2. Des conditions plus complexes</u></center>

Il est possible d'élaborer des structures conditionnelles plus complexes grâce aux opérateurs : NOT, AND, OR, NAND, NOR.

Prenons un exemple, et récupérons **les valeurs de notre matrice qui sont à la fois paires et supérieures à 6**.

**Rappel** : l'opérateur **ET** en Python s'écrit **&** (éperluette)

In [31]:
matrice_b[(matrice_b % 2 == 0) & (matrice_b > 6)]

array([ 8, 10, 12, 14, 16])

Les éléments qui sont pairs et supérieurs à 6 dans matrice_b sont au nombre de 5 : 8, 10, 12, 14, 16.

Continuons avec un exemple utilisant l'opérateur **OU**.

- Récupérer les éléments **inférieurs à 5 ou supérieurs ou égal à 10**.

In [32]:
matrice_b[(matrice_b < 5) | (matrice_b >= 10)]

array([ 1,  2,  3,  4, 10, 11, 12, 13, 14, 15, 16])

Continuons avec un exemple utilisant l'opérateur **ET** et **OU**.

Récupérer **les éléments qui sont divisibles par 2 et par 3 ou les éléments qui sont supérieurs à 15**.

In [38]:
matrice_b[((matrice_b % 2 == 0) & (matrice_b % 3 == 0)) | (matrice_b > 15)]

array([ 6, 12, 16])

 # <center>V.2. Un point sur les dimensions</center>

On va utiliser une nouvelle matrice pour effectuer nos démonstrations.

L'écriture suivante va nous donner un nombre entier.

In [3]:
matrice_v3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [4]:
type(matrice_v3[0,0])

numpy.int32

En revanche, si on tape : [0,0:1], on va obtenir un **vecteur**.

In [5]:
type(matrice_v3[0,0:1])

numpy.ndarray

Et si on tape : [0:1, 0:1], on va obtenir une **matrice**.

In [6]:
type(matrice_v3[0:1, 0:1])

numpy.ndarray

In [7]:
print(matrice_v3[0,0])
print(matrice_v3[0,0:1])
print(matrice_v3[0:1, 0:1])

1
[1]
[[1]]


In [8]:
print(matrice_v3[0,0].shape)
print(matrice_v3[0,0:1].shape)
print(matrice_v3[0:1, 0:1].shape)

()
(1,)
(1, 1)


### <center><u>La méthode np.squeeze()</u></center>

Cette méthode nous permet d'uniformiser le résultat selon la notation que l'on utilise pour récupérer un élément d'un ndarray.

In [9]:
print(matrice_v3[0,0].squeeze())
print(matrice_v3[0,0:1].squeeze())
print(matrice_v3[0:1, 0:1].squeeze())

1
1
1


In [10]:
print(matrice_v3[0,0].squeeze().shape)
print(matrice_v3[0,0:1].squeeze().shape)
print(matrice_v3[0:1, 0:1].squeeze().shape)

()
()
()


Grâce à cette méthode, la **dimension redevient la même** (dimension 0). On peut ainsi effectuer des opérations sans se soucier des dimensions renvoyées par la notation que l'on a choisi pour récupérer un élément d'un ndarray.

Il est également possible d'utiliser **np.squeeze()** pour uniformiser le résultat. A vous de choisir l'écriture que vous préférez.

In [13]:
print(np.squeeze(matrice_v3[0,0]))
print(np.squeeze(matrice_v3[0,0:1]))
print(np.squeeze(matrice_v3[0:1,0:1]))

1
1
1
